"""Added IP address

Revision ID: 159944e855c0
Revises: 
Create Date: 2024-10-19 13:56:42.145843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159944e855c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
